### ISSUE TITLE
Slowdown in game, but full FPS

### ISSUE THREAD

**Issue by Darkmatter569** [libretro/pcsx_rearmed#142]
I was playing some psx games on my raspberry pi 3, and for the most part they run really good. However, crash team racing, and spyro: year of the dragon both have some issues with low fps, which I know for a fact are not present on the actual system.

The frame rate counter reports full 60 FPS, so it is not the emulator struggling. Using the non-libretro version of pcsx-rearmed, and using the speed hacks option to increase the CPU speed to 100 (default is set at 57), the games run perfect.

I use a fresh copy of retropie 4.3, and using NTSC versions of the games. Settings are all on default.

It is almost as if the core purposely underclocks the PSX CPU lower than what it should be, which would explain why increasing it fixes the issue. If this CPU overclock option could be added to the libretro version's rgui menu, this could solve the problem.

**Comment by Darknior** [comment]
Thanks 
Good report, i think you are real. This option can help for some games.
Now we must found a coder than want and know how to implement it.

**Comment by Darkmatter569** [comment]
No problem. I hope someone can help us out, and I look forward to the future of this project.

**Comment by ijfw** [comment]
I am having a similar issue when using the libretro PCSX ReArmed core, but with Ridge Racer games (Turbo, Revolution, and Rage Racer; all games meant to run at 60fps). The emulator reports 60fps, but there is clearly slowdown occuring internally.
As @Darkmatter569 mentioned, the FPS slowdown is solvable when using the standalone non-libretro PCSX ReArmed and adjusting the PSX CPU speed to 100.
I hope that in the near future, this PSX CPU speed hack is made visible to the RetroArch/Lakka front-end.
Thanks to all of you guys and gals for your hard work on this fantastic project!

**Comment by Darknior** [comment]
With same cpu 100% option than lr version on standalone there are no slowdown?... Arg what is bugging on lr...

**Comment by ijfw** [comment]
Yes, with the same cpu 100% option on standalone...
I'd call it a minor annoyance rather than a major bug though; 99% of my game library runs amazingly well using Lakka 2.1 on a Pi 3: I'd call that a win for the lr team!

**Comment by Darknior** [comment]
Yes for sure. The more important bug that is bad for some games is the non visible pop-up. Impossible to use game menu..

**Comment by Darkmatter569** [comment]
True, the sound doesn’t stutter, and the games are definitely still playable if you are willing to overlook the slowdown. I read on some other forum that one user changed a line of code for the default clock speed, and compiled it himself to fix that. Apparently it worked, but some games ran a little faster than they should, which is why that menu option would be more practical, to fine tune as needed.

Also, sorry to bring up another topic within a topic, but does anyone have a PS4 controller? I wouldn’t mind using the standalone emulator, but with my PS4 controller, it doesn’t configure properly and has extreme input lag. If anyone has tested this, or has managed to get it working, please let me know!

@Darknior you mean the bug that makes the selections on the pause menus invisible? Yeah, I’ve seen that one occur in crash bash notably. None of the graphics settings seem to help it.

Here’s hoping for some more awesome updates!

**Comment by Darknior** [comment]
> which is why that menu option would be more practical, to fine tune as needed.

Yes it will be the best way ... i really stand for it :)

> Yeah, I’ve seen that one occur in crash bash notably. 

Yes it is, and some other ...
Like you i really hope some one will continue to work on this great emulator to upgrade the compatibility :D

**Comment by Darkmatter569** [comment]
Sure thing. The line was

 #define PSXCLK 33868800

Located in libpcsxcore/psxcommon.h

The numbers represent the clock speed, and the user adjusted them higher until he could resolve the issue.

**Comment by Kelduum** [comment]
Thought so.

After a fair bit of investigation, bumping that value up quite a bit starts breaking other things, but doesn't resolve the issue in the one instance with clear issues - the NTSC-US version of the R4 Ridge Racer Turbo demo disc thing - still clearly has the issue, and even the in-game clock runs slow.

From the comments around that line, I suspect it's an issue with the dynamic recompiler and a handful of instructions (or even something like DMA, based on it happening at locations on the track, rather than specific timing) taking longer than it should, which is dropping the speed of the simulation to a fraction of what it should be, whereas the game itself (and it's rendering) runs at normal speeds.

The same this is happening at the same places in the original Ridge Racer, and a bunch of other games at the moment, but it's not as obvious as it's simply the speed of the game slowing without dropping frames.

It may be the issue seen with @Darkmatter569 is the same one, and it's simply more prevalent with the Ridge Racer titles, but I can't confirm as I don't have the relevant games, but it would make sense if it's the action of loading the next area in which is causing the slowdown, or simply that the relevant value has been assumed somewhere in the new dynarec code.

Either way, I'll see if I can submit a fix the default speed issue on the non-libretro version, as there's no reason it should be running below 100% of speed on even reasonably modern hardware by default.

**Comment by ZacharyFoxx** [comment]
In Rage Racer, if we keep the mirror rear activated, we will see the game running in slow motion in some parts of the circuits, even with the fps indicating 60fps. Disabling the mirror rear solved this issue. I don´t know if this has relation with the problem related here.

**Comment by emuchicken** [comment]
In the config file, you can actually alter the CPU core % ... Unsure if it helps the issue at all. I'm having issues with Ridge Racer (or RRR)

**Comment by ZacharyFoxx** [comment]
Yeap, I can confirm, changing the CPU clock to 80 resolve the slowdown in Rage Racer and RR4

**Comment by Darknior** [comment]
It's really fantastic because from some weeks i can see many code update of this emulator and a great game compatibility work from every one :)
News options have been added to core options and many games are fixed.
BUT it's hard to remember all these tricks, what option to use with a game or an other?

- Is it plan to add to this GIT CORE an Google XLS witch list the non working fine games with default options, and the core option/trick to fix them ?

Thanks a lot

**Comment by notaz** [comment]
The CPU clock can now be changed in the menus. If some game needs tuning you can create a new issue with your suggestion and it will be added to defaults for that game.
