### ISSUE TITLE
[Bug] Driver (PAL) : cannot "retry"

### ISSUE THREAD

**Issue by RaydenX93** [libretro/pcsx_rearmed#148]
Hi,

I observed an issue in Driver (PAL) game.
The "retry" option is quitting the game rather than retrying the mission.

Note: I play with r22 version.

**Comment by leosmeira** [comment]
This error ocurrer in "Driver - You Are the Wheelman (USA) (v1.1)"

The game quits when you access Menu > Try Again

**Comment by Loquo** [comment]
This error keep in the last commit. Not only Try Again quit the game, also there is no any sound during the intro scene.

**Comment by AnotherLife** [comment]
The Retry crash is a well known bug, try using savestates. Load one when failing a mission and never press Retry.

**Comment by AssCabbage** [comment]
Just to say, someone tagged this bug in a commit recently (I think January?) indicating that it was fixed. However unfortunately it's still there.

One of the greatest PS1 games is still broke :/

**Comment by AnotherLife** [comment]
I don't see any message on this thread referencing a commit. Shouldn't github have added it automatically?

**Comment by AssCabbage** [comment]
I think this must have multiple reports. I can't find the one that tags a recent fix.

**Comment by gameblabla** [comment]
This should be fixed since https://github.com/libretro/pcsx_rearmed/commit/fbf19ce6b6c02da47a67f58e23d8294cfcd18f55 dated May 2020, so after people complained it wasn't working.
I have refined the fix as of https://github.com/libretro/pcsx_rearmed/commit/d2e271b26ef7e8c61a371fe5fa71003e7691118e as it is quite time sensitive and the titlescreen music in Driver was starting right away rather than 24~ frames later.

I'm closing this since this is fixed.
