### ISSUE TITLE
Controller problems

### ISSUE THREAD

**Issue by ghost** [libretro/pcsx_rearmed#182]
Using a .cue an a .bin I have added No Fear Downhill Mountain Biking to retropie but it will not react to my controller except to open the retroarch menu, with the right combinations of buttons. The controller works fine and the other psx game I have is running fine. Does anyone know why and how to fix it?

**Comment by oxr463** [comment]
[retroarch__2020_11_25__12_41_24.log](https://github.com/libretro/pcsx_rearmed/files/5598429/retroarch__2020_11_25__12_41_24.log)

Device: Moto G7
OS: Android 10
Core Version: `r22 15cfb55`

**Comment by AnotherLife** [comment]
I can confirm I have no input (tried it on Windows)

I am using real BIOS

**Comment by oxr463** [comment]
> I can confirm I have no input (tried it on Windows)
> 
> I am using real BIOS

I switched cores to DuckStation, which works fine; but that core doesn't support my save file, (`.srm`).

**Comment by negativeExponent** [comment]
this old issue has nothing to do with latest pcsx_reamed. this is related to long standing issue that is related to Koro Koro Nin and has been fixed already. Current input problems are easily remedied if Multitap1 and 2 are set to none or disabled. Input type selectors are now moved where it should be, that is Settings > Input > Port Controls

**Comment by oxr463** [comment]
> this old issue has nothing to do with latest pcsx_reamed. this is related to long standing issue that is related to Koro Koro Nin and has been fixed already. Current input problems are easily remedied if Multitap1 and 2 are set to none or disabled. Input type selectors are now moved where it should be, that is Settings > Input > Port Controls

This did fix it for me! Is this documented anywhere?

**Comment by negativeExponent** [comment]
see docs.libretro.com. it should be there, if not clearly by notes at least

@twinaphex @hunterk please close.

**Comment by oxr463** [comment]
> see docs.libretro.com. it should be there, if not clearly by notes at least
> 
> @twinaphex @hunterk please close.

I don't see it, https://docs.libretro.com/library/pcsx_rearmed/#multitap

**Comment by AnotherLife** [comment]
I installed the Retroarch Playtest on Steam and the problem is fixed, good job NegativeExponent!

I couldn't find any Multitap options so I guess they are disabled by default so that's why it works. I even enabled that core option to show more input options but I still cannot find any Multitap option anywhere. I looked in Settings>Input, I looked into Controls, I looked into Port 1 controls ... what a jungle Retroarch is ...

**Comment by negativeExponent** [comment]
the default for new core config files is set to **disabled**.
for previous users, older pcsx_rearmed core, the default was set to **auto**, which means that if any inputs types are set on player 3-8 other than **none**, multitaps will get enabled. Some games do not like it. Due to the move of input type selectors from core options (where they should not belong) to proper Settings > Input, Retroach always sets Retropad (any attemp to set **None** as default does not work so far) as default causing old config that are set on **auto** to enable multitaps.

**Multitap1/2** core option should be there when **Show other inputs** is enabled. You need to close the quick menu, then enter quickmenu again for the options to refresh.

Some rework is still to follow for these, along some other input issues i found but atm, can't access PC and my usual resources to do it. For now, just set multitap1/2 to disable if not playing multitap-aware games.

**Comment by negativeExponent** [comment]
this should be working in latest commits

@twinaphex @hunterk @hizzlekizzle
