### ISSUE TITLE
Fantastic Pinball Kyuutenkai - Black screen after selecting Memory Card

### ISSUE THREAD

**Issue by Denshadego** [libretro/pcsx_rearmed#229]
Tecmo logo shows up, then a screen where you select memory card.
![eb49246c-3a1d-11e6-9f0f-41cb1207aa72](https://user-images.githubusercontent.com/47835860/53132119-80225b80-354d-11e9-8bf3-6e7244f47784.png)
(image from another user with the same issue on beetlepsx, where it got resolved)

No matter what you choose, screen goes black after it.

**Comment by AnotherLife** [comment]
How did it get resolved on beetlepsx?

**Comment by LordPinkerton** [comment]
I'd really love a resolution to this as well, as this is an amazingly underrated game.

**Comment by retro-wertz** [comment]
> I'd really love a resolution to this as well, as this is an amazingly underrated game.

use official bios (if you are not using one already...) and try enabling or disabling 2nd memory card (restarting core after each option change.)

**Comment by LordPinkerton** [comment]
> use official bios (if you are not using one already...) and try enabling or disabling 2nd memory card (restarting core after each option change.)

I've used each of the compatible bins for the emulator including scph101.bin, scph7001.bin, scph5501.bin, and scph1001.bin going so far as to verify they were correct by their md5 signature. Enabling or disabling the 2nd memory card option had no effect. No graphic or emulator setting is resolving this issue.

As AnotherLife alluded to, beetle-psx-libretro somehow resolved this particular issue in one of their builds from between Jun 2016 and Oct 2017, according to an issue thread they had on that git. https://github.com/libretro/beetle-psx-libretro/issues/70
 However, since  this is for my RetroPie, using beetle-psx-libretro is not an option.

**Comment by retro-wertz** [comment]
no promises... but ill take note of this...

**Comment by negativeExponent** [comment]
- is this still an issue with latest commit?
- what device/platform/os?
- with official bios? hle?
- full logs? (enable DEBUG for both frontend and core logging)

**Comment by negativeExponent** [comment]
ok.. hacked my way into it and compile 64-bit linux binary. see if it works or if causes issues instead for other games.

[pcsx_rearmed_libretro_x64_linux.zip](https://github.com/libretro/pcsx_rearmed/files/5493276/pcsx_rearmed_libretro_x64_linux.zip)

![pcsx](https://user-images.githubusercontent.com/54053706/98222996-76908f80-1f8c-11eb-8ba8-2de0a4087288.png)

**Comment by SeraphisCain** [comment]
Any updates on this? Game still doesn't work on standard 32-bit RetroPie.

**Comment by gameblabla** [comment]
Guys, i have made further changes to my Fantastic Pinball fix but i would need your help.
If you have an ARM platform like Android, OSX ARM64, a Vita or a jailbroken iOS device... Then i would need someone to test my changes :
https://git.libretro.com/libretro/pcsx_rearmed/-/pipelines/55099

I want to know whenever there is a noticeable delay for the CDDA music or not.
