### ISSUE TITLE
NBA Live 2001 freezes on menu

### ISSUE THREAD

**Issue by AnotherLife** [libretro/pcsx_rearmed#232]
As soon as you reach the menu after the intro videos the game freezes. When googling I saw comments about several people that seem to indicate all NBA Live games from 99 onwards are unplayable. Why is this happening?

**Comment by retro-wertz** [comment]
use bios file

**Comment by AnotherLife** [comment]
I am using bios files. Can you test any NBA Live from 99 to 2003?

**Comment by retro-wertz** [comment]
i just tested NBA 2001 Live and i dont have this crash on menu.. although im using on linux 

![screenshot_2019-03-08_12-59-51](https://user-images.githubusercontent.com/23315382/54008716-dd9be680-41a2-11e9-89e2-7f07bcf96c5c.png)

**Comment by AnotherLife** [comment]
So you are running without Dynarec? Maybe that's why it doesn't freeze.

It is a well known problem it seems, you can find many people talking about NBA Live 99 and onwards not working and they never seem to get them to work or other people saying they work for them. 

Example
https://forum.recalbox.com/topic/3760/no-nba-live-game-is-working-on-psx-emulator/14

These five games are probably using the same gfx or audio library and the same piece of code  causes the freeze in all of them. Too bad because they are the best basketball games on the PSX.

**Comment by bslenul** [comment]
Yeah looks like it's due to the dynarec, someone had the same issue with NBA Live 98 and 2000 on the SNES Mini subreddit: https://www.reddit.com/r/miniSNESmods/comments/am13b3/ps1_nba_live_98_and_2000_wont_work_please_help/

**Comment by retro-wertz** [comment]
i think any dynarec-build can switch to interpreter using core options. maybe that can be confirmed if this issue is dynarec related then...

**Comment by bslenul** [comment]
Ah sorry, instead of leaving the link I should have explain :p 

So basically someone said that he couldnt run NBA Live 98 and 2000 on the SNES Mini (we have dynarec ON for it, or else its way too slow), so I tried and I couldnt get paste the 1st loading screen for 98 and couldnt get controller to work for 2000. But by turning OFF the dynarec and restarting the games, they worked just fine, super slow of course but I could start a match in both games!

&nbsp;

A few other games have trouble with dynarec ON:

* Pro Pinball series apparently (I only tried Pro Pinball - Big Race USA personally).
* Parasite Eve 2 (even with the fix ON in the core options).
* Abe's Exoddus, it says "Incorrect Disc Inserted" when switching discs on the US version.
* Sheep Raider freeze on the tutorial level.

**Comment by bslenul** [comment]
@retro-wertz that CPU clock core option from the latest PR looks really good for dynarec users!

I tested a few games by setting the option at 70 instead of the default 57, on both SNES Classic and my Android phone:
* NBA Live 98: couldnt get controller to work before, works fine now.
* NBA Live 2000: froze at the end of the first loading screen before, works fine now.
* NBA Live 2001: froze when entering main menu before, works fine now.
* Parasite Eve 2: froze on camera change before, works fine now.
* Abe's Exoddus: "Incorrect Disc Inserted" when switching disc before before, works fine now.

The only one that still isnt working is Sheep Raider, even at 100 it still makes RA crash (yup, it doesnt simply freeze like the other ones). If I make a save state before the crash and load it, it doesnt crash at this point anymore but will crash again later in the same level.

For Pro Pinball I think its due to the NEON plugin, because dynarec ON/OFF doesnt change anything and the game runs fine on Windows.

Havent tested each game long enough to tell if theres any downside to changing the option but so far so good, thanks for the update! ❤️

**Comment by retro-wertz** [comment]
that sounds good. thanks for the feedback. any confirmed value past 100 that fixes other games?

**Comment by bslenul** [comment]
I'm not aware of too many other games with dynarec problems, only 3 where it doesnt help unfortunately:

* Driver: freeze when you hit "Restart" (ingame pause menu, not in RA).
* Star Wars Jedi Power Battles: freeze after ~30 seconds of gameplay (sometimes with the music still going on).
* WWF In Your House: crash before the match starts.

But I'll keep messing with this core option if I see anyone having a freeze/crash with dynarec.

**Comment by AnotherLife** [comment]
PSX cycle option to 70 fixes this, thanks!

(Tested on the Playstation Classic)
