### ISSUE TITLE
[ios] - PCSX REARMED crash (ios 8.1.2 ipad air 2 jailbroken with TAIG)

### ISSUE THREAD

**Issue by bsauvage1** [libretro/pcsx_rearmed#26]
as described in old (now closed) issue below:
https://github.com/libretro/RetroArch/issues/2712

PSX cores Mednafen and PCSX REARMED interpreter work well, however the non-interpreter version crashes to desktop.

**Comment by bsauvage1** [comment]
thank you very much - just done

**Comment by adespoton** [comment]
Dynarec will only work on iOS 6 and earlier, and isn't being updated.  Maybe this core should have the default set to Interpreter so that the quick menu can be loaded for further configuration?  Right now you have to edit the config file elsewhere and load it into the RetroArch folder to get things working.

**Comment by meepingsnesroms** [comment]
This is an IOS issue not a core or RetroArch issue.
IOS will not allow data execution,some jailbreaks fix this some dont.
Thats the whole principle of dynarecs,to convert the ROM from ps1 MIPS to host code(ARMv7 in this case),this code is stored in a buffer of writable data.
IOS security forbids the execution of writable code,blame apple.
