### ISSUE TITLE
Formula One 2001

### ISSUE THREAD

**Issue by VGkav** [libretro/pcsx_rearmed#268]
game id is SCES03404

Both on the PSC and on my PC the following thing happens: Everything seems fine until the race starts. Then the game looks and sounds fine but it seems totally broken programmatically, the car immediately lunges forward, instantly goes backwards, the other cars don't move ... the car goes crazy like the physics are broken!

**Comment by retro-wertz** [comment]
can't really expect every game to run on pcsx with zero issue/problems. did you test this at least with standalone version so we can isolate if this is upstream issue or just libretro port problem or if the psc version or any of the options helps?

(wished someone could link the most latest game compatibility listings and or consodilate the game-related issues else there will be hundreds of per game posts arising)

**Comment by AnotherLife** [comment]
This issue is not dynarec related and it's not neon related ... plus, it's a crazy bug lol!

I have not found a good compatibility guide and am intending to make an issue for every broken game I encounter, I thought it'd be neat. I don't expect them to be fixed, just to archive long-standing problems. You don't agree? There are dozens of issues that should be closed.

**Comment by gameblabla** [comment]
This game, as well as F1 2000 and F1 99, are a bit infamous because according to senquack because it's playing with the small cache memory.
https://github.com/senquack/pcsx4all/commit/541f00ba07baaaec467ae61be32b66a92e534023

However (at least using upstream PCSX Rearmed and on x86_64 with the interpreter), the game actually works fine. I don't have the AI & Controls issue.
However, one game i can't run is Formula 99 and it seems to do the same trick.
Supposedly this commit fixes it but it still crashes after the loading screen (it directly references Formula One 2001) :
https://github.com/gameblabla/pcsx_rearmed/commit/004e3057fdad5f375ba6008a3315f5c7bf775fac

However for me the game works just fine without it but F1 99 still crashes for me. (i redumped it from my original copy, even reusing the SBI out there and nothing)

I doubt the dynarec even handles the cache trickery, though i haven't tried the ARM version with this game yet.

**Comment by AnotherLife** [comment]
It will probably work with the interpreter but it would be too slow on my Playstation Classic. And why would I use pcsx-rearmed on my desktop? :D

**Comment by dankcushions** [comment]
because that’s how we diagnose issues. previously you said:

> This issue is not dynarec related

why?

**Comment by AnotherLife** [comment]
If you look at my original post, I tested it on Windows, too. I forgot about that! So I concluded that if the same problem exists in Windows (which uses the intepreter) and in the ARM version, then the dynarec is not at fault.

**Comment by gameblabla** [comment]
> If you look at my original post, I tested it on Windows, too. I forgot about that! So I concluded that if the same problem exists in Windows (which uses the intepreter) and in the ARM version, then the dynarec is not at fault.

That could also mean that both are affected by the issue, not just the dynarec....
which is why i suggested any one of you to try pcsx rearmed with the commit below (as the comment suggests it fixes Formula One 2001 in particular)
https://github.com/gameblabla/pcsx_rearmed/commit/004e3057fdad5f375ba6008a3315f5c7bf775fac

However it could also be possible that it's another issue because it works fine on mainline pcsx rearmed but seemingly not on the libretro version... so perhaps they broke PCSX rearmed somehow ?

**Comment by decadent** [comment]
BTW, the old PCSX-Reloaded with x86 Dynarec has the same issues with this game, on Mac.

**Comment by gameblabla** [comment]
I have a PR that fixes this game for the interpreter and lightrec:
https://github.com/libretro/pcsx_rearmed/pull/545

It won't fix the ARMv7 dynarec however : it will need icache emulation like PCSX4ALL has for its MIPS dynarec.

**Comment by mjw6150** [comment]
> This game, as well as F1 2000 and F1 99, are a bit infamous because according to senquack it's playing with the cache.
> [senquack/pcsx4all@541f00b](https://github.com/senquack/pcsx4all/commit/541f00ba07baaaec467ae61be32b66a92e534023)
> 
> However (at least using upstream PCSX Rearmed and on x86_64 with the interpreter), the game actually works fine. I don't have the AI & Controls issue.
> However, one game i can't run is Formula 99 and it seems to do the same trick.
> Supposedly this commit fixes it but it still crashes after the loading screen (it directly references Formula One 2001) :
> [gameblabla@004e305](https://github.com/gameblabla/pcsx_rearmed/commit/004e3057fdad5f375ba6008a3315f5c7bf775fac)
> 
> However for me the game works just fine without it but F1 99 still crashes for me. (i redumped it from my original copy, even reusing the SBI out there and nothing)
> 
> I doubt the dynarec even handles the cache trickery, though i haven't tried the ARM version with this game yet.
> 
> Try the patch, give the game a try over the interpreter and see if that fixes it for you ?

I would love to play Formula One 2000 and 2001 on my retropie but have same issues listed. I am not very experienced at this sort of thing so can you or anybody kindly give me a step by step instruction to get it to work?

**Comment by gameblabla** [comment]
> I would love to play Formula One 2000 and 2001 on my retropie but have same issues listed. I am not very experienced at this sort of thing so can you or anybody kindly give me a step by step instruction to get it to work?

You could try it by downloading the artifacts here :
https://git.libretro.com/libretro/pcsx_rearmed/-/pipelines/54859

Formula One 2000 still won't run (unrelated to instruction cache unfortunately) and F1 2001 will only run in pure interpreter mode. F1 Arcade will run on both lightrec and interpreter (and not ARM).
Sadly, someone competent enough will need to fix lightrec/arm and add instruction cache emulation to them, not competent enough to do that besides the interpreter.

**Comment by gameblabla** [comment]
As of https://github.com/libretro/pcsx_rearmed/commit/7a8117168d6b9ad083757e013049c0e45734f3fb, this is fixed in interpreter mode.
This game will behave the same on lightrec/ARM dynarec however, so you'll still have the car going around like crazy on those.
Unfortunately, i would need someone to add icache support to these.

**Comment by notaz** [comment]
There is now a hack for the ARM dynarec, and other platforms can switch to the interpreter to play this game.

**Comment by pcercuei** [comment]
I don't have that game, but I think it is fixed now in the master branch.
