### ISSUE TITLE
Running in 240p omits lines

### ISSUE THREAD

**Issue by fluxens** [libretro/pcsx_rearmed#272]
When running pcsx_rearmed with retropie in 240p mode (with pi2scart) there are lines missing on screen. However they are rendered (screenshots and higher Aspect Ratio Heigth show the missing lines).

https://imgur.com/a/anf8Gi6

To reproduce launch WipeOut 2097/XL. In Options > Load and Save check the empty memory card slots. All should be labeled "E", however the first row is labeled "C", caused by a missing lines. 

Custom Aspect Ratio Width 1600
Custom Aspect Ratio Height 240
Window Scale 3.0
Integer Scale ON

Version 1.7.6 r22

config.txt
dtoverlay=vga666
disable_audio_dither=1
enable_dpi_lcd=1
display_default_lcd=1
dpi_group=2
dpi_mode=87
hdmi_timings=320 1 16 30 34 240 1 2 3 22 0 0 0 60 0 6400000 1

**Comment by Sakitoshi** [comment]
looks like you need to take a look at your configs, is working as intended on my end.

[https://imgur.com/cYanXYn](https://imgur.com/cYanXYn)
it's harder to see because I have a 14inch tv but is definitely an "E".

one difference is that I'm not using any fancy device, just plain old composite direct from the pi's jack.

**Comment by hizzlekizzle** [comment]
ah, yeah, if it's PAL, it's probably 288p instead of 240p.

**Comment by fluxens** [comment]
@Sakitoshi you are correct. just tried the ntsc version. Everything looks good. Closing this as it is not a pcsx_issue.
