### ISSUE TITLE
Worms Pinball - Black Screen

### ISSUE THREAD

**Issue by dan18774** [libretro/pcsx_rearmed#331]
Everytime i load Worms Pinball with lr-pcsx-rearmed or PCSX-ReARMed i'm greeted with a black screen. Tested the rom with pSX v1.13 emulator on my pc and it works 10 - 15 sec black screen then loads up fine. Tried turning the bin file to pbp format still loads to black screen. I have added all the bios files scph1001.bin , scph101.bin , scph7001.bin , and scph5501.bin. The inside of the cue file matches the bin file. Thanks if anyone can take few secs to look at this or not.

Pi 3 Model B +
RetroPie Version Used: 4.4
just updated Libretro pcsx rearmed

**Comment by gameblabla** [comment]
The game's black screen issue was fixed with my CDROM timings changes (https://github.com/libretro/pcsx_rearmed/commit/068a6133171b026956bbfd91e9bf4666def8823d).

However, the game then crashes (at least on x86_64 interpreter) when it tries to get to the memory card screen.
Upstream with the libpicofe frontend, the game would briefly display some corruption and still play fine after. (https://github.com/notaz/pcsx_rearmed/issues/196)
On libretro however, when it is supposed to show the corruption, it crashes instead.

When i got the crash in notaz's version, it was crashing in gpulib and the function do_vram_line.

I guess we should close this bug report and open another one.
