### ISSUE TITLE
Vagrant Story black screen

### ISSUE THREAD

**Issue by nomoredarts** [libretro/pcsx_rearmed#332]
Between two cut scenes the second one is not loaded. Instead there is only black screen.
Screenshot shows the moment before blank. This is like 2,5h in game, right after Flame Dragon fight.

![Vagrant Story (USA)-190811-155929](https://user-images.githubusercontent.com/6137314/62839556-bedad800-bc8b-11e9-9e3f-3860cbbf947c.png)

Pi 3 Model B +
RetroPie Version Used: 4.4
Libretro pcsx rearmed up to date.

**Comment by AnotherLife** [comment]
Does it get stuck there? Is the game unfinisheable?

**Comment by nomoredarts** [comment]
It's impossible to finish the game. After blank there is nothing. All I can do is load state or close emulator. I've tested it also in RetroArch on Android with the same result.

**Comment by negativeExponent** [comment]
if it worked on beetle psx, does it means that's because its using official bios(beetle has to)? can you upload savestate and savefile for this area?

**Comment by AnotherLife** [comment]
@nomoredarts 

Were you using real bios files?

**Comment by nomoredarts** [comment]
@AnotherLife yes, I have basically tried everything. With and without bios. I've even tried to "fix" save file by changing it in hex editor.

@negativeExponent Save state and save file in attachment.

[state.zip](https://github.com/libretro/pcsx_rearmed/files/3562193/state.zip)

**Comment by negativeExponent** [comment]
thanks for the state file.. so here's what i found...

the savefile (.srm) is probably broken or this is saved is for a different region of the game coz i cannot load it. im using the game with serial **SLUS-01040**
So, ill have to rely on the savestate file instead. and i indeed confirmed that it gets stuck in the FMV.

I've concluded that this is because you were not using an official bios(savestates includes the bios used so iif you were using HLE, it will load with HLE bios despite if you booted the core with official psx one).

so what i did, is load the save game, went to the nearest save area and create a savegame. i exited PCSX_Rearmed, made sure a bios file exists. run pcsx (confirming that the bios was found and loaded). load the save game, and tada, no crash on fmv

![Screenshot_2019-08-31_17-11-06](https://user-images.githubusercontent.com/54053706/64061844-6b1c3880-cc12-11e9-9d34-31c8b47868b9.png)

No PCSX users should rely on running this core on HLE. compatibility is not so great and some issues are not noticeable until later in game.

**Comment by notaz** [comment]
I've loaded the memcard in HLE mode and it passed the cutscenes so this appears to be fixed.
