### ISSUE TITLE
Crashes on 3DS

### ISSUE THREAD

**Issue by Alaharon123** [libretro/pcsx_rearmed#384]
#This tracker is for pcsx-rearmed-libretro issues *only*.

If the issue also occurs in standalone PCSX-ReARMed, the upstream repo is probably a better place for it.

##Description

Crashes on 3DS. I'm including a bunch of crash logs from testing in the past week, but I don't remember details for all of them. They're from Final Fantasy Origins and Kartia: The Word of Fate. I'm going to include steps to reproduce for Kartia: The Word of Fate because I got multiple crashes in the same spot. Not sure which of the crash reports they are though other than log 16.

##Steps to reproduce

How can we reproduce this issue? Please include all relevant steps, as well as any settings that you have changed from their default values, particularly including whether you are using the dynarec or interpreter CPU emulation.

Default settings on 3ds iirc. afaik that uses dynarec. To trigger the crash in Kartia: The Word of Fate (and I've done this three times with success every time): Start the game, play through the first level (takes about 30 minutes), and sometime around beating the boss of the level, whether that's right before, when you hit save, or some other time right around when you should be finishing the level, the system will crash with a prefetch abort.

##When did the behavior start?

I've only tested Kartia on 1.8.4 stable and the 2020-02-17 nightly. I've tried Final Fantasy Origins on some nightly pre-1.7.9 and probably 1.8.1, but I'm not including crash reports because I don't remember many details. That game is more stable than it was then, but it still crashes every so often.

##Your device/OS/platform/architecture

New 3DS XL on latest firmware, latest boot9strap, latest luma, latest godmode9, etc. Used the cia version of retroarch for all versions mentioned in the behavior section.

Crash reports: [arm11.zip](https://github.com/libretro/pcsx_rearmed/files/4214791/arm11.zip)

**Comment by m4xw** [comment]
You didn't provide the binaries, without them the crash reports are just hot air.
Pointing at nightlies isn't sufficient, please upload them, copied from your device.

Also include screenshots of the exception screens, as I have no clue in which format the dmp files are.

**Comment by Alaharon123** [comment]
Alright, made it crash again with the same process. Actually crashed slightly earlier this time. Attaching picture of crash from 3ds and crash log. If someone can give me instructions on copying the binary from my 3ds, I can do that too. I don't currently know how to do that and Google was not able to tell me.

Picture: ![P_20200218_204932](https://user-images.githubusercontent.com/34926441/74794362-f9ec4280-5290-11ea-9a2c-40fdae3895ed.jpg)
Log: [crash_dump_00000017.zip](https://github.com/libretro/pcsx_rearmed/files/4222743/crash_dump_00000017.zip)

**Comment by justinweiss** [comment]
These are the mostly random dynarec crashes that have been happening for a long time. They tend to be prefetch aborts with PC somewhere around 0x004XXXXX, and have 16 bytes of 0xFF in a row in the stack dump. When the core is running, 0x004XXXXX seems to be in the memory block reserved by the dynarec, which is why I suspect some problem happening in there.
I'm surprised there hasn't been an issue opened on this already -- this one is as good as any to have a discussion.

Unfortunately, these prefetch aborts happen more or less randomly. They don't break into the debugger like data aborts do, so I can't inspect the state of memory when it crashes. They force a reset of the system, so any on-system logging gets lost, and I don't know of a good way to do remote logging on the 3DS. I haven't been able to get any breadcrumbs to follow from the register data or the stack, although that's probably because I just don't know enough about how the dynarec works. Is there a way to get the 3DS to core dump on a crash? A memory snapshot would be hugely helpful for figuring this out.

This dynarec came from mupen64plus, right? Could there maybe have been bugfixes in that version that haven't been ported back to this one? Are there other systems using this dynarec that have random crashes? They seem to happen more frequently under heavy load, so maybe other systems are just more powerful enough not to run into them? Although that might just be randomness playing its usual tricks.

I'd also be interested in knowing whether there are older versions of the core that don't have this problem -- bisection would be helpful. I've tried looking at the code a few times, but if it were something obvious, it would be happening much more often.

**Comment by justinweiss** [comment]
And just after I write that, I find some breadcrumbs in the stack. The last two crashes I got had these things in the stack / registers:

- `ctr_invalidate_ICache_kernel`
- `ctr_flush_DCache_kernel`
- `needs_clear_cache`
- `cop1_usable`

If it's crashing in supervisor mode, that would probably explain why it's not breaking into the debugger. Not super helpful, but at least a little more to go on.

I have the reports and a symbolized .elf saved off, if anyone ends up wanting to take a look. These happened in Chrono Cross, loading the map after winning battles.

**Comment by m4xw** [comment]
Yea these symbols are more what I expected.
Throw me the elf + the offsets @justinweiss

**Comment by justinweiss** [comment]
I think I found a fix. PR is here: https://github.com/libretro/pcsx_rearmed/pull/390

**Comment by twinaphex** [comment]
@Alaharon123 The next version (probably up tomorrow on the buildbot) will have an updated PCSX ReARMed core with this issue hopefully fixed. The only precondition is that you need to use Luma3DS.

Let us know if this resolves the issue, and in specific @justinweiss.

**Comment by MrHuu** [comment]
Could this be related to the crashes experienced with gPSP dynarec?

'Dynarec Crashes on "New" 3DS' #36

**Comment by justinweiss** [comment]
@MrHuu gpsp uses mostly the same 3ds_utils functions, so I would guess it’s the same problem with the same solution. I just haven’t had time to test the fix over there yet.

**Comment by Alaharon123** [comment]
Sorry for late reply. Tested twice the sequence that was able to crash it consistently and it didn't crash either time! Gonna finish Final Fantasy I via Final Fantasy Origins within the next... period of time. Thanks for the fix @justinweiss!

**Comment by DragonautMk** [comment]
> Sorry for late reply. Tested twice the sequence that was able to crash it consistently and it didn't crash either time! Gonna finish Final Fantasy I via Final Fantasy Origins within the next... period of time. Thanks for the fix @justinweiss!

Can you try again with latest stable of retroarch and latest stable of luma 3ds 10.1.1?
(I guess you are using luma.)

**Comment by justinweiss** [comment]
@Alaharon123 Have you experienced any of these crashes lately? I haven't heard any reports myself, so I think this can be closed.

**Comment by Alaharon123** [comment]
I ended up finishing Final Fantasy I on pc because I'd played so much of it there so I haven't been playing ps1 on 3ds, but the testing I did after that commit it didn't crash so I assume the problem is fixed. Unfortunately I don't have any ps1 games coming up on my backlog rn for me to play on 3ds. I think the issue is fixed though. Feel free to close it and if I have an issue at some point in the future, I'll make a new issue now that I know where that issue should go. Seems fixed though
