### ISSUE TITLE
CHD no longer supported?

### ISSUE THREAD

**Issue by LordPinkerton** [libretro/pcsx_rearmed#412]
#This tracker is for pcsx-rearmed-libretro issues *only*.

If the issue also occurs in standalone PCSX-ReARMed, the upstream repo is probably a better place for it.

##Description

Retroarch crashes everytime I load a CHD file, though I never had this problem with v.r22 7375bf9. Are the no longer supported in r22 14e45ca?

##Steps to reproduce

Load any CHD converted from cue/bin.

##When did the behavior start?

After updating to latest core build r22 13e45ca.

##Your device/OS/platform/architecture

Switch running Atmosphere 0.12.0 and OS version 9.2.0.

**Comment by negativeExponent** [comment]
is this guaranteed to be a CHD problem? how many times did you try loading the same CHD and still get a crash? does cue/bin work all the time without fail? also this core requires official bios to be used when Dynarec(lightrec) is used, which is the case with your device. I have a standing issue about it causing freezing in linux but might be a crash for some systems.

**Comment by LordPinkerton** [comment]
It's possible the build I was using noted above had the issue, as after I updated to v.r22 4857be4, the problem reported seems to not longer be an issue. Closing.

**Comment by negativeExponent** [comment]
i can guess what you problems were. 

1. you do not have an official bios file, which means you are using interpreter build instead of lightrec.
2. as i have said earlier, there is an issue i posted using the lightrec build that can cause core to freeze and maybe crashed for some system. It can happen during loading a game at some cases or the turning Dynarec on/off.
