### ISSUE TITLE
LIGHTREC / Winning Eleven 2002 (Windows and Android), Crashes Retroarch.

### ISSUE THREAD

**Issue by Denshadego** [libretro/pcsx_rearmed#457]
When playing World Soccer Winning Eleven 2002 (Japan) (And any mod made with it as a base), the game loads fine, exhibition games can be played, but when trying to play any other mode (League, cup, master league) retroarch crashes to desktop/home, just before the game is about to load.

Happens on both windows 10 and android, tried with or without shaders, same result. I'm attaching a log.

[retroarch.log](https://github.com/libretro/pcsx_rearmed/files/5393148/retroarch.log)

![1](https://user-images.githubusercontent.com/47835860/96299492-868b0400-0fca-11eb-92fa-02dcb74addc0.png)
![2](https://user-images.githubusercontent.com/47835860/96299501-88ed5e00-0fca-11eb-8cf0-78970a2ccb25.png)

**Comment by negativeExponent** [comment]
can you re-take log but this time set log level to DEBUG for both frontend and core? (dunno how much info we can see since a lot of them has been either removed or hidden nowadays).
just out of curiosity, can you test with HLE bios only, and a separate test using scph1001.bin (this should not matter but using psxonpsp.bin might have different startup timings than regular ones).
and to reduce size of log, can probably turn off shaders for the test.
thanks.

**Comment by demodanza** [comment]
Here it is with the log at debug level, shaders off, but shader info logs anyway somehow, crash. 
[retroarch.log](https://github.com/libretro/pcsx_rearmed/files/5418701/retroarch.log)
However, when setting the bios to HLE, the crash doesn't happen! Here's the log too:
[retroarchHLE.log](https://github.com/libretro/pcsx_rearmed/files/5418722/retroarchHLE.log)

**Comment by negativeExponent** [comment]
> However, when setting the bios to HLE, the crash doesn't happen! Here's the log too:
This is rather interesting piece of note. Can you retest again using any official bios, but this time switch Dynarec off.

If this does not crash, then try updating both retroarch and pcsx, this game probably has issue with dynarec, so just switch it off for this game. your pc should still run fast without it.

**Comment by demodanza** [comment]
Tried with dynarec off and no crashes. I'm leaving it that way, thanks!

**Comment by negativeExponent** [comment]
dont close. maybe something can be fixed on the LIGHTREC side. suggest to rename topic and add LIGHTREC and reopen

@twinaphex

**Comment by negativeExponent** [comment]
reconfirmations is needed here:

i was able to test in linux and every combination just works on my end
- with or without official bios
- with or without dynarec (lightrec)
- with or without multitap
- different controller types
- using latest commit, and the commit before the recent input fixes

on my end, game just works.

**Comment by demodanza** [comment]
That's weird, I'll test again on my devices, however, I noticed in the latest core updates, there's a lot of games where there's no input, doesn't matter what you set in controls. Had to go back to a backup I had of the core to be able to play.

I did not start another issue because seeing this game work on your end made me think it may be something wrong on my setups (though in that case a backup's input wouldn't work, but I don't know). I found another report of the recent input issues here https://www.reddit.com/r/gpdxd/comments/jogjsd/couple_of_issues_pcsx_rearmed_and_ps_remote_play/

I'll be back after I make some further testing.

**Comment by negativeExponent** [comment]
inputs have changed. they are now configurable in settings>input instead of core options.

side effect though, ports are always occupied as "standard" controller by default, so this messes things up for some games when multitap1/2 is set to auto.

You need to set multitap1/2 from core options to "default" for non-multitap games.

**Comment by gameblabla** [comment]
I guess we can consider this solved ?

**Comment by notaz** [comment]
No response, assuming fixed.
