### ISSUE TITLE
Android - Some games have slowdowns, although the RA shows 60 FPS

### ISSUE THREAD

**Issue by ZacharyFoxx** [libretro/pcsx_rearmed#78]
Before the updates which happened around September 9th, the PCSXReArmed was at the same level of performance than ePSXe.
After September 9th, first the core was broken and now some games presents slowdowns, even with the RA showing 60FPS like Rage Racer and Dead or Alive.
Rage Races had already slowdowns if you keep the rear mirror actived, but you only needed turn the option off. Now, the game shows slowdowns ever if you turn it off.
With Dead or Alive, the performance of game is worse than before.
I tried the same versions of RA and the core, both in the Ouya as in the Nexus 5, having the same results.

I have no idea how build the core but I can test it!

PS: Sorry, I closed the previous issue by mistake when I was responding a post of notaz.

**Comment by joolswills** [comment]
Including @frangarcj  as related to their code:

I can confirm this on the Raspberry Pi 

bisected as much as possible - had to skip a few commits due to non building

```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
73081f238a4d80891cf9df5aebeebe3d13c84144
74f9b36fd4ac10413edf74992d5a92ac74dcc441
d8f2e2d88a0f951388b894e3edea0d44a54727dd
We cannot bisect more!
```

So looks to be related to the VITA changes in these commits - commit 8c57409c2962a24b7d888000d77f0ec462487c56 works at full speed.

... Looking at those commits I noticed a line that looked out of place.

https://github.com/libretro/pcsx_rearmed/commit/73081f238a4d80891cf9df5aebeebe3d13c84144#diff-bcc93185b5af1efadbbb0318c53fe7ecR1580

I reverted this and speed is back again

here's the diff - will submit a PR

```diff
diff --git a/frontend/libretro.c b/frontend/libretro.c
index f9be756..44cb974 100644
--- a/frontend/libretro.c
+++ b/frontend/libretro.c
@@ -1598,7 +1598,6 @@ void retro_init(void)
    if(!__ctr_svchax)
       Config.Cpu = CPU_INTERPRETER;
 #endif
-  Config.Cpu = CPU_INTERPRETER;
 
        ret |= emu_core_init();
        if (ret != 0) {
```

**Comment by Fadi5555** [comment]
Please can you enable dynarec on iOS as well please?
We get JIT on jailbroken iOS 9 functionality but we didn't get dynarec port of pcsx until now.
Thanks.
