### ISSUE TITLE
F1 2000 (USA) (EA)

### ISSUE THREAD

**Issue by CometHunter92** [libretro/pcsx_rearmed#858]
### PCSX-ReARMed Version

2b455e2ec087079cf2d84571e38ec49e963fb777

### Your device

Pi4

### Operating System of your device

Linux (or Linux-based like RetroPie etc.)

### CPU architecture

ARM 64bit (AArch64)

### Issue description

There is a very nitpicking accuracy issue in the time trial mode. Restarting a time trial brings you back to the menu when crossing the start/finish line. This prevents restarting a time trial after exiting it. Tried different CPU clock values, same thing, it happens on interpreter too.

### Step-by-step reproduction and logs

Enter a time trial, no need to finish the lap, just start it. No need to insert initials for the record neither. Cross the starting/finish line. Pause the time trial, "Quit". Re-enter the time trial. Just as before, no need to insert initials. Start the lap, as soon as the start/finish line is crossed you are pushed back to the menu.

**Comment by notaz** [comment]
The game has somewhat bugged cdrom code, and also what seems to be a mod protection where it kicks you out to the menu if it detects the game was hacked. This even applies to the US version, even though that doesn't have libcrypt protection. However what happens in the emulator is that it reads the wrong sector due to bad timing and treats that as a hack.

I've added a hack for the specific case you reported, but there might be more so more testing is needed.

**Comment by CometHunter92** [comment]
Thanks for the insights! I close it for now, I'll test it more in the next days.
