### ISSUE TITLE
Multiline cheats on RetroArch

### ISSUE THREAD

**Issue by uniQ168** [libretro/pcsx_rearmed#90]
Hi,

I was just setting up a Raspberry Pi 3 with RetroPie 4.1 the other day and tried emulating PSX games with lr-pcsx-rearmed abaa8b9. I messed around with some gameshark cheats and it worked, but I can't seem to get multiline cheats working. Running the codes one by one is a bit of a clumsy process. ^^'
Am I doing something wrong?

This is working:
```
cheats = 2

cheat0_desc = "Infinite Ammo Claire (1/2)"
cheat0_code = "800D49F5+0063"
cheat0_enable = "true"

cheat1_desc = "Infinite Ammo Claire (2/2)"
cheat1_code = "800D4A01+0063"
cheat1_enable = "true"
```

This is not:
```
cheats = 1

cheat0_desc = "Infinite Ammo Claire"
cheat0_code = "800D49F5+0063+800D4A01+0063"
cheat0_enable = "true"
```

**Comment by uniQ168** [comment]
Nobody? ^^'

**Comment by fr500** [comment]
cheats have never been high on our priorities...

**Comment by loganmc10** [comment]
@ilag11111 has some experience with cheats, perhaps you can convince him to look into it?

**Comment by uniQ168** [comment]
It might not be the most important feature, but maybe there is a quick fix to this. :)

**Comment by ilag11111** [comment]
I haven't looked at PCSX as far as cheats are concerned.  I did look at Mednafen, but it doesn't look like baseline mednafen even supports multiline cheats.  Since I don't emulate PS1 games on ARM, I haven't bothered to try anything on reARMed.  As long as the base core supports multiline cheats, I can throw together the needed functions to plug in retroarch cheats.  Looks like PCSX does, and almost all of the hard work has already been done.  Shouldn't take me too long to put in a pull request and at least get some progress in.
